name: urate

networks:
  utec_net:
    driver: bridge

services:
  # ── MICROSERVICIO 1: Users 
  ms-users:
    build: ./ms-users
    container_name: utec_ms_users
    restart: unless-stopped
    networks: [utec_net]
    ports: ["3001:3001"]
    environment:
      DATABASE_URL:       ${DATABASE_URL:-postgresql://postgres:postgres@DB_HOST:5432/auth_db}
      JWT_SECRET:         ${JWT_SECRET:-utec_rate_secret_2025_change_me}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-utec_rate_refresh_2025_change_me}
      PORT:               3001
      NODE_ENV:           production
      CORS_ORIGIN:        "*"

  # ── MICROSERVICIO 2: Academic 
  ms-academic:
    build: ./ms-academic
    container_name: utec_ms_academic
    restart: unless-stopped
    networks: [utec_net]
    ports: ["3002:3002"]
    environment:
      DB_URL:   ${MYSQL_URL:-jdbc:mysql://DB_HOST:3306/academic_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8}
      DB_USER:  ${MYSQL_USER:-utec_user}
      DB_PASS:  ${MYSQL_PASS:-utec_pass_2025}
      MS1_URL:  http://ms-users:3001
      MS1_MOCK: "false"
      SERVER_PORT: 3002
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      ms-users:
        condition: service_started


  # ── MICROSERVICIO 3: Reviews+Repos 
  ms-reviews:
    build: ./ms-reviews
    container_name: utec_ms_reviews
    restart: unless-stopped
    networks: [utec_net]
    ports: ["3003:3003"]
    environment:
      MONGO_URL: ${MONGO_URL:-mongodb://DB_HOST:27017}
      MONGO_DB:  reviews_db
      MS1_URL:   http://ms-users:3001
      MS2_URL:   http://ms-academic:3002
    depends_on:
      ms-users:
        condition: service_started
      ms-academic:
        condition: service_started


  # ── MICROSERVICIO 4: Content/Orquestador 
  ms-content:
    build: ./ms-content
    container_name: utec_ms_content
    restart: unless-stopped
    networks: [utec_net]
    ports: ["3004:3004"]
    environment:
      PORT:    3004
      MS1_URL: http://ms-users:3001
      MS2_URL: http://ms-academic:3002
      MS3_URL: http://ms-reviews:3003
    depends_on:
      ms-users:
        condition: service_started
      ms-academic:
        condition: service_started
      ms-reviews:
        condition: service_started


  # ── MICROSERVICIO 5: Analytics 
  ms-analytics:
    build: ./ms-analytics
    container_name: utec_ms_analytics
    restart: unless-stopped
    networks: [utec_net]
    ports: ["3005:3005"]
    environment:
      MS1_URL:               http://ms-users:3001
      MS2_URL:               http://ms-academic:3002
      MS3_URL:               http://ms-reviews:3003
      S3_BUCKET:             ${S3_BUCKET:-utecrate-analytics-data}
      AWS_REGION:            ${AWS_REGION:-us-east-1}
      AWS_ACCESS_KEY_ID:     ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN:     ${AWS_SESSION_TOKEN:-}
      ATHENA_DATABASE:       ${ATHENA_DATABASE:-utecrate}
      ATHENA_OUTPUT:         ${ATHENA_OUTPUT:-s3://utecrate-analytics-data/athena-results/}
    depends_on:
      ms-users:
        condition: service_started
      ms-academic:
        condition: service_started
      ms-reviews:
        condition: service_started


  # ── NGINX: balanceador interno
  nginx:
    image: nginx:alpine
    container_name: utec_nginx
    restart: unless-stopped
    networks: [utec_net]
    ports: ["80:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ms-users
      - ms-academic
      - ms-reviews
      - ms-content
      - ms-analytics
